In [1]:
#数据归一化
from sklearn.preprocessing import MinMaxScaler
data=[[-1,2],[-0.5,6],[0,10],[1,18]]

scaler =MinMaxScaler()
scaler=scaler.fit(data)
result =scaler.transform(data)

result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [11]:
scale_=MinMaxScaler(feature_range=[5,10])
result_=scale_.fit_transform(data)

In [12]:
result_

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [4]:
scale_.inverse_transform(result_)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [20]:
#数据标准化
from sklearn.preprocessing import StandardScaler
data=[[-1,2],[-0.5,6],[0,10],[1,18]]
scaler=StandardScaler()
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [21]:
scaler.var_  #查看方差属性 var_

array([ 0.546875, 35.      ])

In [22]:
scaler.mean_  #查看均值属性mean_

array([-0.125,  9.   ])

In [24]:
x_std=scaler.transform(data)

In [25]:
x_std


array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [26]:
x_std.mean()

0.0

In [27]:
x_std.std()

1.0

In [33]:
##缺失值填补

import pandas as pd
data=pd.read_csv(r"/Users/lijianwei/Desktop/菜菜sklearn/day08_Narrativedata.csv",index_col=0)

In [35]:
data.head()


Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         714 non-null float64
Sex         891 non-null object
Embarked    889 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [37]:
#用0，平均值，中位数填补缺失值
from sklearn.impute import SimpleImputer
data["Age"].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [40]:
Age=data["Age"].values.reshape(-1,1)

In [45]:
import numpy as np
#用0填补缺失值
imp_0=SimpleImputer(missing_values=np.nan,strategy="constant",fill_value=0)
imp_0=imp_0.fit_transform(Age)

#用平均值填补缺失值
imp_mean=SimpleImputer(missing_values=np.nan,strategy="mean").fit_transform(Age)

#用中位数填补缺失值
imp_median=SimpleImputer(missing_values=np.nan,strategy="median").fit_transform(Age)

In [44]:
imp_0

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [ 0.  ],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [ 0.  ],
       [31.  ],
       [ 0.  ],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [ 0.  ],
       [19.  ],
       [ 0.  ],
       [ 0.  ],
       [40.  ],
       [ 0.  ],
       [ 0.  ],
       [66.  ],
       [28.  ],
       [42.  ],
       [ 0.  ],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [ 0.  ],
       [ 3.  ],
       [19.  ],
       [ 0.  ],
       [ 0.  ],
       [ 0.  ],
       [ 0.  ],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [ 0.  ],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [

In [46]:
imp_mean

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [29.69911765],
       [54.        ],
       [ 2.        ],
       [27.        ],
       [14.        ],
       [ 4.        ],
       [58.        ],
       [20.        ],
       [39.        ],
       [14.        ],
       [55.        ],
       [ 2.        ],
       [29.69911765],
       [31.        ],
       [29.69911765],
       [35.        ],
       [34.        ],
       [15.        ],
       [28.        ],
       [ 8.        ],
       [38.        ],
       [29.69911765],
       [19.        ],
       [29.69911765],
       [29.69911765],
       [40.        ],
       [29.69911765],
       [29.69911765],
       [66.        ],
       [28.        ],
       [42.        ],
       [29.69911765],
       [21.        ],
       [18.        ],
       [14.        ],
       [40.        ],
       [27.        ],
       [29.69911765],
       [ 3.        ],
       [19.        ],
       [29

In [47]:
imp_median

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [28.  ],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [28.  ],
       [31.  ],
       [28.  ],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [28.  ],
       [19.  ],
       [28.  ],
       [28.  ],
       [40.  ],
       [28.  ],
       [28.  ],
       [66.  ],
       [28.  ],
       [42.  ],
       [28.  ],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [28.  ],
       [ 3.  ],
       [19.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [28.  ],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [

In [48]:
data["Age"]=imp_median

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         891 non-null float64
Sex         891 non-null object
Embarked    889 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [50]:
#缺失值比较少值 我们可以直接删除
data=data.dropna()

In [51]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 4 columns):
Age         889 non-null float64
Sex         889 non-null object
Embarked    889 non-null object
Survived    889 non-null object
dtypes: float64(1), object(3)
memory usage: 34.7+ KB


In [52]:
data

Age     Sex Embarked Survived
0    22.0    male        S       No
1    38.0  female        C      Yes
2    26.0  female        S      Yes
3    35.0  female        S      Yes
4    35.0    male        S       No
5    28.0    male        Q       No
6    54.0    male        S       No
7     2.0    male        S       No
8    27.0  female        S      Yes
9    14.0  female        C      Yes
10    4.0  female        S  Unknown
11   58.0  female        S      Yes
12   20.0    male        S       No
13   39.0    male        S       No
14   14.0  female        S       No
15   55.0  female        S  Unknown
16    2.0    male        Q       No
17   28.0    male        S      Yes
18   31.0  female        S       No
19   28.0  female        C      Yes
20   35.0    male        S  Unknown
21   34.0    male        S      Yes
22   15.0  female        Q      Yes
23   28.0    male        S      Yes
24    8.0  female        S       No
25   38.0  female        S  Unknown
26   28.0    male        C       No
27   19.0    male        S       No
28   28.0  female        Q      Yes
29   28.0    male        S       No
..    ...     ...      ...      ...
861  21.0    male        S       No
862  48.0  female        S      Yes
863  28.0  female        S       No
864  24.0    male        S  Unknown
865  42.0  female        S  Unknown
866  27.0  female        C  Unknown
867  31.0    male        S       No
868  28.0    male        S       No
869   4.0    male        S      Yes
870  26.0    male        S       No
871  47.0  female        S  Unknown
872  33.0    male        S       No
873  47.0    male        S       No
874  28.0  female        C      Yes
875  15.0  female        C      Yes
876  20.0    male        S       No
877  19.0    male        S       No
878  28.0    male        S       No
879  56.0  female        C      Yes
880  25.0  female        S      Yes
881  33.0    male        S       No
882  22.0  female        S       No
883  28.0    male        S  Unknown
884  25.0    male        S       No
885  39.0  female        Q       No
886  27.0    male        S       No
887  19.0  female        S      Yes
888  28.0  female        S       No
889  26.0    male        C  Unknown
890  32.0    male        Q       No

[889 rows x 4 columns]

In [59]:
#处理分类数据特征
#preprocessing.LabelEncoder: 标签专用，能够将标签转换为分类数值
from sklearn.preprocessing import LabelEncoder
y=data.iloc[:,-1]
le=LabelEncoder()
le.fit(y)

LabelEncoder()

In [60]:
le.classes_

array(['No', 'Unknown', 'Yes'], dtype=object)

In [61]:
label=le.transform(y)

In [62]:
label

array([0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       2, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2,
       0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 0, 0,
       2, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0, 1,
       0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0, 2,
       0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1, 0,
       0, 1, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 2,
       0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2,

In [63]:
le.inverse_transform(label)

array(['No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes',
       'Unknown', 'Yes', 'No', 'No', 'No', 'Unknown', 'No', 'Yes', 'No',
       'Yes', 'Unknown', 'Yes', 'Yes', 'Yes', 'No', 'Unknown', 'No', 'No',
       'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No',
       'No', 'Yes', 'No', 'No', 'No', 'Unknown', 'Yes', 'No', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'No', 'Yes', 'Unknown', 'No', 'Unknown',
       'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Unknown', 'Yes',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes',
       'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'No', 'Unknown', 'No', 'No', 'Yes', 'No', 'No', 'Ye

In [64]:
 #preprocessing.OrdinalEncoder   特征专用，能够将分类特征转换为分类数值
from sklearn.preprocessing import OrdinalEncoder
data_=data.copy()
data_.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [67]:
OrdinalEncoder().fit(data_.iloc[:,1:-1]).categories_

[array(['female', 'male'], dtype=object), array(['C', 'Q', 'S'], dtype=object)]

In [68]:
data_.iloc[:,1:-1]=OrdinalEncoder().fit_transform(data_.iloc[:,1:-1])

In [69]:
data_.head()

Age  Sex  Embarked Survived
0  22.0  1.0       2.0       No
1  38.0  0.0       0.0      Yes
2  26.0  0.0       2.0      Yes
3  35.0  0.0       2.0      Yes
4  35.0  1.0       2.0       No

In [74]:

#对于名义变量，我们需要使用独热编码（哑变量） preprocessing.OnHotEncoder
from sklearn.preprocessing import OneHotEncoder
X=data.iloc[:,1:-1]
enc=OneHotEncoder().fit(X)
result=enc.transform(X).toarray()
result

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [75]:
#获取特征名称 get_feature_names
enc.get_feature_names()

array(['x0_female', 'x0_male', 'x1_C', 'x1_Q', 'x1_S'], dtype=object)

In [76]:
newdata=pd.concat([data,pd.DataFrame(result)],axis=1)
newdata

Age     Sex Embarked Survived    0    1    2    3    4
0    22.0    male        S       No  0.0  1.0  0.0  0.0  1.0
1    38.0  female        C      Yes  1.0  0.0  1.0  0.0  0.0
2    26.0  female        S      Yes  1.0  0.0  0.0  0.0  1.0
3    35.0  female        S      Yes  1.0  0.0  0.0  0.0  1.0
4    35.0    male        S       No  0.0  1.0  0.0  0.0  1.0
5    28.0    male        Q       No  0.0  1.0  0.0  1.0  0.0
6    54.0    male        S       No  0.0  1.0  0.0  0.0  1.0
7     2.0    male        S       No  0.0  1.0  0.0  0.0  1.0
8    27.0  female        S      Yes  1.0  0.0  0.0  0.0  1.0
9    14.0  female        C      Yes  1.0  0.0  1.0  0.0  0.0
10    4.0  female        S  Unknown  1.0  0.0  0.0  0.0  1.0
11   58.0  female        S      Yes  1.0  0.0  0.0  0.0  1.0
12   20.0    male        S       No  0.0  1.0  0.0  0.0  1.0
13   39.0    male        S       No  0.0  1.0  0.0  0.0  1.0
14   14.0  female        S       No  1.0  0.0  0.0  0.0  1.0
15   55.0  female        S  Unknown  1.0  0.0  0.0  0.0  1.0
16    2.0    male        Q       No  0.0  1.0  0.0  1.0  0.0
17   28.0    male        S      Yes  0.0  1.0  0.0  0.0  1.0
18   31.0  female        S       No  1.0  0.0  0.0  0.0  1.0
19   28.0  female        C      Yes  1.0  0.0  1.0  0.0  0.0
20   35.0    male        S  Unknown  0.0  1.0  0.0  0.0  1.0
21   34.0    male        S      Yes  0.0  1.0  0.0  0.0  1.0
22   15.0  female        Q      Yes  1.0  0.0  0.0  1.0  0.0
23   28.0    male        S      Yes  0.0  1.0  0.0  0.0  1.0
24    8.0  female        S       No  1.0  0.0  0.0  0.0  1.0
25   38.0  female        S  Unknown  1.0  0.0  0.0  0.0  1.0
26   28.0    male        C       No  0.0  1.0  1.0  0.0  0.0
27   19.0    male        S       No  0.0  1.0  0.0  0.0  1.0
28   28.0  female        Q      Yes  1.0  0.0  0.0  1.0  0.0
29   28.0    male        S       No  0.0  1.0  0.0  0.0  1.0
..    ...     ...      ...      ...  ...  ...  ...  ...  ...
861  21.0    male        S       No  1.0  0.0  0.0  0.0  1.0
862  48.0  female        S      Yes  0.0  1.0  0.0  0.0  1.0
863  28.0  female        S       No  1.0  0.0  0.0  0.0  1.0
864  24.0    male        S  Unknown  1.0  0.0  1.0  0.0  0.0
865  42.0  female        S  Unknown  0.0  1.0  0.0  0.0  1.0
866  27.0  female        C  Unknown  0.0  1.0  0.0  0.0  1.0
867  31.0    male        S       No  0.0  1.0  0.0  0.0  1.0
868  28.0    male        S       No  0.0  1.0  0.0  0.0  1.0
869   4.0    male        S      Yes  1.0  0.0  0.0  0.0  1.0
870  26.0    male        S       No  0.0  1.0  0.0  0.0  1.0
871  47.0  female        S  Unknown  0.0  1.0  0.0  0.0  1.0
872  33.0    male        S       No  1.0  0.0  1.0  0.0  0.0
873  47.0    male        S       No  1.0  0.0  1.0  0.0  0.0
874  28.0  female        C      Yes  0.0  1.0  0.0  0.0  1.0
875  15.0  female        C      Yes  0.0  1.0  0.0  0.0  1.0
876  20.0    male        S       No  0.0  1.0  0.0  0.0  1.0
877  19.0    male        S       No  1.0  0.0  1.0  0.0  0.0
878  28.0    male        S       No  1.0  0.0  0.0  0.0  1.0
879  56.0  female        C      Yes  0.0  1.0  0.0  0.0  1.0
880  25.0  female        S      Yes  1.0  0.0  0.0  0.0  1.0
881  33.0    male        S       No  0.0  1.0  0.0  0.0  1.0
882  22.0  female        S       No  0.0  1.0  0.0  0.0  1.0
883  28.0    male        S  Unknown  1.0  0.0  0.0  1.0  0.0
884  25.0    male        S       No  0.0  1.0  0.0  0.0  1.0
885  39.0  female        Q       No  1.0  0.0  0.0  0.0  1.0
886  27.0    male        S       No  1.0  0.0  0.0  0.0  1.0
887  19.0  female        S      Yes  0.0  1.0  1.0  0.0  0.0
888  28.0  female        S       No  0.0  1.0  0.0  1.0  0.0
889  26.0    male        C  Unknown  NaN  NaN  NaN  NaN  NaN
890  32.0    male        Q       No  NaN  NaN  NaN  NaN  NaN

[891 rows x 9 columns]

In [77]:
newdata.drop(["Sex","Embarked"],axis=1,inplace=True)
newdata.columns=["Age","Survived",'Female', 'Male', 'Embarked_C', 'Embarked_Q', 'Embarked_S']
newdata.head()

Age Survived  Female  Male  Embarked_C  Embarked_Q  Embarked_S
0  22.0       No     0.0   1.0         0.0         0.0         1.0
1  38.0      Yes     1.0   0.0         1.0         0.0         0.0
2  26.0      Yes     1.0   0.0         0.0         0.0         1.0
3  35.0      Yes     1.0   0.0         0.0         0.0         1.0
4  35.0       No     0.0   1.0         0.0         0.0         1.0

In [79]:
#处理连续性特征：二值化与分段 preprocessing.Binarizer
data_2=data.copy()
from sklearn.preprocessing import Binarizer
X=data_2.iloc[:,0].values.reshape(-1,1)
transformer=Binarizer(threshold=38).fit_transform(X)#######threshold 为阈值
transformer

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [80]:
#处理连续性变量，能够将连续性变量排序后按顺序分箱处理  preprocessing.KBinsDiscretizer
from sklearn.preprocessing import KBinsDiscretizer

X=data.iloc[:,0].values.reshape(-1,1)
est=KBinsDiscretizer(n_bins=3,encode='ordinal',strategy='uniform')     ##encode编码方式：onehot、ordinal    strategy用来定义箱宽方式：uniform(等宽分箱)、quantile（等位分箱）、kmeans（聚类分箱）
est.fit_transform(X)

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],

In [ ]:
set(est.fit_transform(X).ravel())  ##ravel（）降纬  